version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:8.2.2-alpine
    ports:
      - "6379:6379"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    volumes:
      - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./init/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "15672:15672"
  configuration-a-service:
    container_name: configuration-a-service
    build:
      context: ./configuration-a-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
  configuration-b-service:
    container_name: configuration-b-service
    build:
      context: ./configuration-b-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped
  temporal:
    container_name: temporal
    build:
      context: ./temporal
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    restart: unless-stopped